### ISSUE TITLE
为什么引入找不到cmp

### ISSUE THREAD

**Issue by Dylanocean8866** [liyiheng/zset#17]
➜  zset go get -u github.com/liyiheng/zset
package cmp: unrecognized import path "cmp": import path does not begin with hostname

**Comment by liyiheng** [comment]
cmp 包是 go1.21 新增的，最新版本依赖了它。
旧版  `go get github.com/liyiheng/zset@v0.1.0`  没依赖它但是不支持泛型。

也许可以把依赖 cmp 的部分实现摘出来，从而支持 go1.18 ~ go1.20 这几个版本

**Comment by liyiheng** [comment]
Fixed by #18
