### ISSUE TITLE
key是否能够支持string

### ISSUE THREAD

**Issue by 137-rick** [liyiheng/zset#7]
key是否能够支持string
目前是int64

**Comment by XanthusL** [comment]
很久以前就在纠结把key换成 string 还是等待go2的泛型。

**Comment by xcl3721** [comment]
> 很久以前就在纠结把key换成 string 还是等待go2的泛型。

期待，我们这本来计划用来存用户uid，结果来了个uuid作为uid的。。。

**Comment by liyiheng** [comment]
https://github.com/liyiheng/zset/pull/16
